### ISSUE TITLE
aggiornamento ammcom.csv

### ISSUE THREAD

**Issue by gjrichter** [ondata/sesso-e-potere#8]
Il Ministero dell'Interno ha aggiornato i file sul sito https://dait.interno.gov.it/elezioni/open-data/amministratori-locali-e-regionali-in-carica al 5 Ottobre 2022. Ho scaricato il file degli 'Amministratori comunali' per controllare se ha meno comuni mancanti del precedente e ho visto progressi nella completezza. 

Uso il file: sesso-e-potere/ dati/amministazioni-italiane/processing/ammcom.csv per alcune mappe. E' possibile aggiornare questo file alla nuova versione?

**Comment by aborruso** [comment]
Fatto caro @gjrichter

**Comment by aborruso** [comment]
Non ho aggiornato, perché non forzavo download e update.

Riapro e domani pubblico tutto
